# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4e324935bf4f9aa589399e525bd046a3f819b026f7e6b0c5256324bac3a95b7564c1cd1d9d87374c32e74897c292d8bdb9e4834ef6663ee1f594c4ff6786b824

test:
  secret_key_base: df245806c376ff6d5ad84967a5f3be7946768d0aa9bc83eccf46cf2d46787267db2e35abed5531e9fed5a81e1971e8b8cd2710c6950b6e1405ad978c3c91c72c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
